<?php
return array (
  118 => 
  array (
    'catid' => '118',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '118,119',
    'catname' => 'Product_mall',
    'Encatname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'Product_mall',
    'url' => 'http://localhost/welshine/en/index.php?m=content&c=index&a=lists&catid=118',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"english","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '118',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'product_mall',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  119 => 
  array (
    'catid' => '119',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '118',
    'arrparentid' => '0,118',
    'child' => '0',
    'arrchildid' => '119',
    'catname' => 'fuwuche',
    'Encatname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'Product_mall/',
    'catdir' => 'fuwuche',
    'url' => 'http://localhost/welshine/en/index.php?m=content&c=index&a=lists&catid=119',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"english","category_template":"category","list_template":"list1","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '119',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'fuwuche',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>